site_name: Woodworking.nl Projecten
site_url: https://woodworking-nl.github.io/projecten/
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/woodworking-nl/projecten
repo_name: woodworking-nl/projecten

copyright: |
  &copy; 2024 <a href="https://woodworking.nl" target="_blank" rel="noopener">woodworking.nl</a>

nav:
  - 'index.md'
  - 'freestafel.md'

theme:
  name: material
  logo: assets/woodworking-logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - toc.follow
    - navigation.top
    # - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: nl
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: custom 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

